-------------------------------------------------------------------------
Fecha: vie sep 16 23:10:55 ART 2016 Host:nelo-linux
-------------------------------------------------------------------------

NVIDIA: no NVIDIA devices found
Traceback (most recent call last):
  File "cupydle/test/dbn_FACE.py", line 27, in <module>
    from cupydle.dnn.dbn import DBN
  File "/run/media/lerker/Documentos/Proyecto/Codigo/cupydle/cupydle/dnn/dbn.py", line 28, in <module>
    import theano
  File "/usr/lib/python3.5/site-packages/theano/__init__.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/usr/lib/python3.5/site-packages/theano/sandbox/cuda/__init__.py", line 697, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/usr/lib/python3.5/site-packages/theano/sandbox/cuda/__init__.py", line 495, in use
    device, cuda_initialization_error_message))
OSError: You forced the use of gpu device gpu, but CUDA initialization failed with error:
Unable to get the number of gpus available: unknown error

-------------------------------------------------------------------------
FINALIZADO Fecha: vie sep 16 23:11:00 ART 2016 
-------------------------------------------------------------------------

